run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocyclo
    - goimports
    - gosimple

linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 10
